<?php

/**
 * @file
 */


/**
 * Implements hook_menu().
 */
function webis_dashboard_menu() {
  $items = array();

  $items['admin/webis_dashboard'] = array(
    'title' => 'Webis Dashboard',
    'description' => "Manage your site contents in one place.",
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'menu_name' => 'management',
    'position' => 'right',
    'weight' => -7,
  );

  return $items;
}
